name: flutter_test_robots
description: Flutter test tools and extensions to simulate human-computer interactions
version: 0.1.0
homepage: https://github.com/flutter-bounty-hunters/flutter_test_robots

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0
  logging: ^1.0.2

flutter:
  # No Flutter config
